# Databricks notebook source
# MAGIC %md
# MAGIC # Step 5a: Create & Configure Databricks App
# MAGIC Creates/reuses the Databricks App, configures app resources,
# MAGIC and generates app.yaml. Runs in PARALLEL with DB provisioning.

# COMMAND ----------

import time
_start = time.time()

dbutils.widgets.text("project_id", "lakemeter-customer")
dbutils.widgets.text("db_name", "lakemeter_pricing")
dbutils.widgets.text("app_name", "lakemeter")
dbutils.widgets.text("secrets_scope", "lakemeter-secrets")
dbutils.widgets.text("claude_endpoint", "databricks-qwen3-next-80b-a3b-instruct")

project_id = dbutils.widgets.get("project_id")
db_name = dbutils.widgets.get("db_name")
app_name = dbutils.widgets.get("app_name")
secrets_scope = dbutils.widgets.get("secrets_scope")
claude_endpoint = dbutils.widgets.get("claude_endpoint")

print(f"Project: {project_id}")
print(f"Database: {db_name}")
print(f"App: {app_name}")
print(f"Secrets scope: {secrets_scope}")
print(f"Claude endpoint: {claude_endpoint}")

# COMMAND ----------

import os
import re
from datetime import datetime
from databricks.sdk import WorkspaceClient
from databricks.sdk.service.apps import App

w = WorkspaceClient()
user = w.current_user.me().user_name
normalized_project_id = re.sub(
    r"[^a-z0-9-]+",
    "-",
    project_id.strip().lower(),
).strip("-")
project_name = f"projects/{normalized_project_id}"
branch_name = f"{project_name}/branches/production"
endpoint_name = f"{branch_name}/endpoints/primary"

# COMMAND ----------

# 1. Set workspace secrets for config values
t0 = time.time()
print("Step 1: Setting workspace secrets...")

try:
    w.secrets.list_secrets(scope=secrets_scope)
except Exception:
    try:
        w.secrets.create_scope(scope=secrets_scope)
        print(f"  Secrets scope '{secrets_scope}' created")
    except Exception as e:
        if "already exists" not in str(e).lower():
            raise

for key, value in {
    "lakebase-project": project_name,
    "lakebase-branch": branch_name,
    "lakebase-endpoint": endpoint_name,
}.items():
    try:
        w.secrets.put_secret(
            scope=secrets_scope,
            key=key,
            string_value=value,
        )
        print(f"  {secrets_scope}:{key} set")
    except Exception as e:
        print(f"  Warning: Could not set {key}: {e}")

print(f"  Done ({time.time() - t0:.1f}s)")

# COMMAND ----------

# 2. Create app if it doesn't exist (this is the SLOW step ~2-3 minutes)
t0 = time.time()
print(f"Step 2: Creating Databricks App '{app_name}'...")

try:
    app_info = w.apps.get(app_name)
    print(f"  App '{app_name}' already exists ({time.time() - t0:.1f}s)")
except Exception:
    print(f"  App not found, creating...")
    try:
        app_obj = App(
            name=app_name,
            description="Lakemeter — Databricks cost estimation tool",
            default_source_code_path=f"/Workspace/Users/{user}/apps/{app_name}",
        )
        w.apps.create_and_wait(app_obj)
        print(f"  App '{app_name}' created ({time.time() - t0:.1f}s)")
    except Exception as e:
        print(f"  Warning: Could not create app: {str(e)[:200]}")
        print("  You may need to create the app manually via the Databricks UI")

# COMMAND ----------

# 3. Prepare app resources (configured after database provisioning)
t0 = time.time()
print("Step 3: Preparing app resources...")

resource_map = {
    "lm-lakebase-project": ("lakebase-project", "Lakebase project"),
    "lm-lakebase-branch": ("lakebase-branch", "Production branch"),
    "lm-lakebase-endpoint": ("lakebase-endpoint", "Primary endpoint"),
    "lm-db-host": ("lakebase-host", "Database host"),
    "lm-db-user": ("lakebase-user", "Database user"),
    "lm-db-name": ("lakebase-database", "Database name"),
}

resources = []
for name, (secret_key, desc) in resource_map.items():
    resources.append({
        "name": name,
        "description": desc,
        "secret": {"scope": secrets_scope, "key": secret_key, "permission": "READ"},
    })

resources.append({
    "name": "lm-claude-endpoint",
    "description": "Claude model endpoint for AI Assistant",
    "serving_endpoint": {"name": claude_endpoint, "permission": "CAN_QUERY"},
})

print(
    f"  Prepared {len(resources)} resource definitions "
    f"({time.time() - t0:.1f}s)"
)

# COMMAND ----------

# 4. Generate app.yaml and write to bundle files path
t0 = time.time()
print("Step 4: Generating app.yaml...")

app_yaml_content = f"""# Databricks App Configuration — generated by installer
# Project: {project_name} | Generated: {datetime.now().isoformat()[:19]}

command:
  - "/bin/bash"
  - "-c"
  - |
    # Start FastAPI backend (frontend is pre-built into backend/static/)
    cd backend && ../.venv/bin/python -m uvicorn app.main:app --host 0.0.0.0 --port ${{DATABRICKS_APP_PORT:-8000}}

env:
  # App environment
  - name: "ENVIRONMENT"
    value: "production"
  - name: "CORS_ORIGINS"
    value: ""

  # Lakebase Autoscaling database configuration
  - name: "LAKEBASE_PROJECT"
    valueFrom: "lm-lakebase-project"
  - name: "LAKEBASE_BRANCH"
    valueFrom: "lm-lakebase-branch"
  - name: "LAKEBASE_ENDPOINT"
    valueFrom: "lm-lakebase-endpoint"
  - name: "DB_HOST"
    valueFrom: "lm-db-host"
  - name: "DB_USER"
    valueFrom: "lm-db-user"
  - name: "DB_NAME"
    valueFrom: "lm-db-name"
  - name: "DB_PORT"
    value: "5432"
  - name: "DB_SSLMODE"
    value: "require"

  # AI Assistant (Claude) model serving endpoint
  - name: "CLAUDE_MODEL_ENDPOINT"
    valueFrom: "lm-claude-endpoint"
"""

nb_context = dbutils.notebook.entry_point.getDbutils().notebook().getContext()
nb_path = nb_context.notebookPath().get()
if not nb_path.startswith("/Workspace"):
    nb_path = "/Workspace" + nb_path
bundle_files_dir = os.path.dirname(os.path.dirname(nb_path))
app_source_dir = os.path.join(bundle_files_dir, "app_source")
app_yaml_path = os.path.join(app_source_dir, "app.yaml")

with open(app_yaml_path, "w") as f:
    f.write(app_yaml_content)
print(f"  app.yaml written to {app_yaml_path} ({time.time() - t0:.1f}s)")

dbutils.jobs.taskValues.set(key="app_yaml_path", value=app_yaml_path)

# COMMAND ----------

elapsed = time.time() - _start
print(f"\nApp creation & configuration complete ({elapsed:.1f}s)")
dbutils.notebook.exit(f"App '{app_name}' configured with {len(resources)} resources ({elapsed:.1f}s)")
